### ISSUE TITLE
Unnecessary/unused/broken functionality is exposed to user officers

### ISSUE THREAD

**Issue by ACLay** [UserOfficeProject/stfc-user-office-project#229] opened 2021-10-14 16:04 UTC
If you sign in with the User Officer role, you can access several pages from the sidebar that have no practical purpose for STFC (at least for now).

"People" and "Institutions" are the stand outs to me, as I'd expect the data here is copied over from our Users environment, and isn't copied back. Even if there was copy back, we don't store details like date of birth, or nationality (these seem to default to the unix epoch and Afghan). We shouldn't be showing editor fields that aren't actually persisted to the users database and are outside the scope of what we're using this app for. The editor page also exposes the contact details of anyone who's ever been on an experiment to anyone with the user officer role. While the user office does have legitimate reasons to access these details, I'm not sure this is the right place to do so.

The people page also has "INVITE USER" and "INVITE REVIEWER" buttons which pop up error messages if used.
![image](https://user-images.githubusercontent.com/2938284/137354426-e12465d3-6961-4a4e-b858-bd7ad96f9234.png)

I'm unsure, but suspect we should also hide the "SEPs" (Scientific evaluation panels) and "Sample safety" options.

**Comment by TickleThePanda** [comment] 2021-10-18 16:59
This is a duplicate of #54

**Closed by TickleThePanda** 2021-10-18 16:59 UTC
Labels: type: gdpr, area: uop/stfc
