### ISSUE TITLE
As a FAP secretary/round manager,  I am able to clone a section of the template rather than the whole thing 

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#131] opened 2021-05-20 12:00 UTC
Requested by David Carroll at CLF stakeholder meeting (14th May 2021). 

Functionality currently not included. Consider where this fits within the project scope. (SP requirement list #98 )

**Comment by TickleThePanda** [comment] 2021-05-24 12:33
Duplicate of #23

**Closed by TickleThePanda** 2021-05-24 12:33 UTC
Labels: area: uop/stfc, status: clarify, triage: duplicate, type: feature
