### ISSUE TITLE
Create an STFC theme

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/stfc-user-office-project#69] opened 2021-02-03 09:02 UTC
We need to create an STFC theme for the user office project.

We need to consider, how to make it reasonably fit in with our existing applications:
 - [ ] colour
 - [ ] logos
 - [x] footer (moved into #141)

This probably needs some input from stakeholders to agree what level of theming this should be.

/overwrite opened 2020-09-04

**Comment by JEThompson97** [comment] 2021-04-20 10:31
In creating the theme, **accessibility should be considered**.
This should include:
- Colour contrast between font and background
- Font size

_Note_: The current theme does **not** meet WCAG standards.

---
The [WAVE tool](https://github.com/isisbusapps/ISISBusApps/wiki/Accessibility#web-page-accessibility-assessment-tools) is a useful way to assess this

**Comment by simonfernandes** [comment] 2021-06-01 14:14
@TickleThePanda What content does the page footer need to contain? I think we might need:

- Link and contact details for ISIS UO
- Link and contact details for CLF UO
- Support email address
- Link to STFC site
- Copyright?
- Terms and conditions?
- Privacy notice?

**Comment by TickleThePanda** [comment] 2021-06-07 10:14
On the proposals sites, we currently have:
![image](https://user-images.githubusercontent.com/13658288/120999781-68ecf380-c781-11eb-8afc-f3dde7afccc0.png)

Let's keep it simple for now and have those.

We can open an issue for a later phase to allow it to do more complex things, if we like.

**Comment by simonfernandes** [comment] 2021-06-23 08:29
I've created a frontend branch for ESS to try out the styling that we've added: `configurable_theme_wip`. In this branch:

- Moved all STFC styling into the main CSS file and used ESS colours
- The theme can access the settings and feature context (although doesn't right now)
- Note that the StylesProvider component has to wrap around the theme, so that the CSS can take priority over the Material UI styling.

When you change role, the page loses its styling until you dismiss the notification. This is caused by an error ('Warning: Can't perform a React state update on an unmounted component'), but I'm not sure how to fix it. There is also a second or two of the default material UI colour on the loading icon when first loading.

Options going forward: 

### Option 1

Mount CSS file(s) in the backend and access it in the frontend. The CSS can contain our site colours which can then be accessed to create the theme.

 - If the CSS is accessed via CDN then the link can be stored in the database. 
 - If the file is always mounted in an agreed location, is there a need to put anything in the database? I don't know how accessing a file would work in this scenario. Maybe a config location would have to be read.
 - Does managing shared CSS become more difficult this way?
 
### Option 2
 
 Store theme information in the database. Should just need colours that can be stored as strings. We can share the same CSS but with different colours.
 
 - We would be storing the colours twice this way (CSS and database) and they could become out of sync

**Comment by ACLay** [comment] 2021-06-24 08:38
> We would be storing the colours twice this way (CSS and database) and they could become out of sync

What if we use something like LESS, and at startup or when the values are changed, (re)generate a colours file and recompile the LESS to CSS? We wouldn't need to store the colours in multiple areas, and all the rest of the styling could be common to all facilities.

**Comment by TickleThePanda** [comment] 2021-06-29 08:28
> What if we use something like LESS, and at startup or when the values are changed, (re)generate a colours file and recompile the LESS to CSS? We wouldn't need to store the colours in multiple areas, and all the rest of the styling could be common to all facilities.

As we have native CSS variables, I think we could avoid using less.

Could we have a default set of variables set in the stylesheet and then overwrite them in JS, by setting the variables on the root element, from the theme? By setting them on the root element's style using JS, I believe they would have a higher specificity.

**Comment by ACLay** [comment] 2021-06-29 08:41
> As we have native CSS variables, I think we could avoid using less.

Ooh, very neat, hadn't come across those before. Looks like there's [no IE support for them though](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#browser_compatibility) Is that something we're no longer after in the new system?

**Comment by TickleThePanda** [comment] 2021-06-29 09:31
As these are style enhancements and CSS rules with `var()` will be ignored, this will fall-back nicely for IE (they would use the default theme instead).

Though, I'm not sure if IE is even supported by the new system - which is something that we need to check and then communicate out to users when we come to deploying.

**Comment by simonfernandes** [comment] 2021-07-14 08:05
Closed via https://github.com/UserOfficeProject/user-office-backend/pull/350 and https://github.com/UserOfficeProject/user-office-frontend/pull/412

**Closed by simonfernandes** 2021-07-14 08:05 UTC
Labels: area: uop/stfc, origin: project, size: 5, type: feature
