### ISSUE TITLE
Resubmission statement not included in final proposal PDF 

### ISSUE THREAD

**Issue by sc19ew** [UserOfficeProject/stfc-user-office-project#314] opened 2022-01-18 14:12 UTC
Details surrounding resubmission do not show in the final PDF of the proposal that will be sent to reviewers, meaning reviewers cannot see the details of the `Explain how you have addressed the reviewers’ comments to result in a materially different submission? ` section in the PDF. 

Opened from a support query stating: "I noticed that the resubmission statement of the online form is not included in the final PDF version of the proposal. If the panel only gets the PDF, they will miss that part."

**Comment by TickleThePanda** [comment] 2022-01-19 09:24
I think we should look at this with some urgency to see if we can get it working before we generate the FAP booklets.

**Comment by TickleThePanda** [comment] 2022-01-26 10:48
Duplicate of #324

**Closed by TickleThePanda** 2022-01-26 10:48 UTC
Labels: origin: project, type: bug, priority: urgent, area: uop/stfc
