### ISSUE TITLE
As a submitter I can attach my DOI making it easier for me to access my publications

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/stfc-user-office-project#134] opened 2021-05-20 12:07 UTC
Requested by Greg Greetham - CLF (LSF)

can they attach "associated publications" in a sensible way? DOI? making it easy for the reviewers to access the publications? PDF? 

Panda confirmed this would be a planned improvement    (SP requirement list #95)

**Comment by TickleThePanda** [comment] 2021-05-24 12:32
Duplicate of #31

**Closed by TickleThePanda** 2021-05-24 12:32 UTC
Labels: area: uop/stfc, origin: project, triage: duplicate, type: feature

**Comment by WhittyPM** [comment] 2021-05-24 12:33
Thanks @TickleThePanda
